### PR TITLE
feat: `on_event` can subscribe to multiple endpoints at once

### PR DESCRIPTION
**Pull request by chubei**
Interface change:

Old:

```proto
// Request for `OnEvent`.
message OnEventRequest {
  // The event type to subscribe to.
  dozer.types.EventType type = 1;
  // The name of the endpoint to subscribe to.
  string endpoint = 2;
  // JSON filter string.
  optional string filter = 3;
}
```

New:

```proto
// Request for `OnEvent`.
message OnEventRequest {
  // The endpoints to subscribe to. Key is the endpoint name, value is the filter.
  map<string, dozer.types.EventFilter> endpoints = 1;
}

// Event filter.
message EventFilter {
  // The event type to subscribe to.
  dozer.types.EventType type = 1;
  // JSON filter string.
  optional string filter = 3;
}
```

### CODE REVIEW

**Comment by snork-alt** [comment]
Would the request look like this @chubei ? 
```
grpcurl -d '{"endpoints": {"trips": {"type": "ALL", "filter": "{\"PULocationID\": 211}"}}}' \
    -plaintext localhost:50051 dozer.common.CommonGrpcService/OnEvent
```

**Comment by chubei** [comment]
@snork-alt 

```bash
grpcurl -d '{ "endpoints": [{ "key": "trips", "value": { "type": "ALL", "filter": "{\"PULocationID\": 211}"} }] }'\
    -plaintext localhost:50051 dozer.common.CommonGrpcService/OnEvent
```

**Comment by chubei** [comment]
@snork-alt this is clearer

```bash
grpcurl -d '{
    "endpoints": [
        {
            "key": "trips",
            "value": {
                "type": "ALL",
                "filter": "{\"PULocationID\": 211}"
            }
        }
    ]
}' -plaintext localhost:50051 dozer.common.CommonGrpcService/OnEvent
```

**Comment by snork-alt** [comment]
Instead of key and value then, why not use `endpoint` and `filter` ?

**Comment by chubei** [comment]
> Instead of key and value then, why not use `endpoint` and `filter` ?

"key" and "value" is just the syntax of proto json to write a `map`. It's not part of our code. See description of the PR.

**Review by snork-alt — APPROVED** [review]

**Pull request merged**
