### PR TITLE
fix: Update .deb url doc

### PR DESCRIPTION
**Pull request by mediuminvader**

### CODE REVIEW

**Comment by snork-alt** [comment]
let's make sure we do not have to manually install protoc

**Review by chloeminkyung — APPROVED** [review]

**Comment by chubei** [comment]
This link doesn't work for me.

```text
root@0bed76927968:/# dpkg -i dozer_linux_x86_64.deb
(Reading database ... 5121 files and directories currently installed.)
Preparing to unpack dozer_linux_x86_64.deb ...
Unpacking dozer (0.1.10) over (0.1.10) ...
dpkg: dependency problems prevent configuration of dozer:
 dozer depends on libssl1.1 (>= 1.1.0); however:
  Package libssl1.1 is not installed.

dpkg: error processing package dozer (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 dozer
```

**Comment by mediuminvader** [comment]
> This link doesn't work for me.
> 
> ```
> root@0bed76927968:/# dpkg -i dozer_linux_x86_64.deb
> (Reading database ... 5121 files and directories currently installed.)
> Preparing to unpack dozer_linux_x86_64.deb ...
> Unpacking dozer (0.1.10) over (0.1.10) ...
> dpkg: dependency problems prevent configuration of dozer:
>  dozer depends on libssl1.1 (>= 1.1.0); however:
>   Package libssl1.1 is not installed.
> 
> dpkg: error processing package dozer (--install):
>  dependency problems - leaving unconfigured
> Errors were encountered while processing:
>  dozer
> ```
> 
> I'm using the `ubuntu:latest` docker image.

the filename should be dozer-linux-x86_64.deb

**Comment by chubei** [comment]
Still have the libssl problem.

```text
root@0bed76927968:/# dpkg -i dozer-linux-x86_64.deb 
(Reading database ... 5121 files and directories currently installed.)
Preparing to unpack dozer-linux-x86_64.deb ...
Unpacking dozer (0.1.13) over (0.1.10) ...
dpkg: dependency problems prevent configuration of dozer:
 dozer depends on libssl1.1 (>= 1.1.0); however:
  Package libssl1.1 is not installed.

dpkg: error processing package dozer (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 dozer
```

**Pull request merged**
