### PR TITLE
fix: Fix check of supported tables in postgres

### LINKED ISSUE #1072: Postgres `get_schemas` throws a runtime error for views.
Postgres breaks during `get_schemas` when source db has `views`. 

The following line breaks as this value is obtained as `NULL`
https://github.com/getdozer/dozer/blob/main/dozer-ingestion/src/connectors/postgres/schema_helper.rs#L295

### PR DESCRIPTION
**Pull request by karolisg**
closes #1072

### CODE REVIEW

**Review by chubei — COMMENTED** [review]
Don't really understand this code

**Comment by karolisg** [comment]
> Don't really understand this code

This PR contains several changes:
1) Validation of table type added to schema helper
2) Did some minor refactorings in schema helper to reduce complex and not clear type definitions
3) Add table type validator 
4) Moved schema tests to separate file
5) Commented kafka tests, because they are not used at the moment

**Comment by chubei** [comment]
> This PR contains several changes:
> 
> 1. Validation of table type added to schema helper
> 2. Did some minor refactorings in schema helper to reduce complex and not clear type definitions
> 3. Add table type validator
> 4. Moved schema tests to separate file
> 5. Commented kafka tests, because they are not used at the moment

Thanks for the explaination! I kind of get what this PR is trying to do. Just don't have enough postgres knowledge to review it.

**Comment by v3g42** [comment]
@karolisg the query takes very long to run. Is this the only way to obtain metadata in SQL

**Comment by karolisg** [comment]
> @karolisg the query takes very long to run. Is this the only way to obtain metadata in SQL

I will solve it in different PR. This one already has a lot changes.

**Review by chloeminkyung — APPROVED** [review]

**Pull request merged**
