### PR TITLE
Implement MySQL connector for Dozer

### PR DESCRIPTION
**Pull request by feliciien**
/claim #1670

### CODE REVIEW

**Comment by snork-alt** [comment]
Connector must be implemented in Rust as all other connectors and adhere to connector trait and requirements

**Comment by feliciien** [comment]
Title: Implement MySQL CDC Connector in Rust for Dozer

Description:
This pull request (PR) aims to implement a MySQL CDC connector in Rust for the Dozer platform. The MySQL CDC connector allows Dozer to capture and process data changes from a MySQL database in real-time. It adheres to the connector trait and requirements, providing seamless integration with the Dozer ecosystem.

Purpose:
The purpose of this PR is to enhance the capabilities of Dozer by adding support for MySQL CDC. MySQL CDC is a critical component for real-time data processing and integration scenarios, allowing applications to react to data changes immediately. By implementing the MySQL CDC connector in Rust, we can leverage the performance, safety, and reliability benefits of Rust while enabling seamless integration with MySQL CDC.

This PR includes the following key components and changes:

Implementation of the MySQLCDCConnector struct: This struct represents the MySQL CDC connector and provides methods for connecting to the MySQL CDC instance, processing data changes, and retrieving change data.
Adherence to the Connector trait: The MySQLCDCConnector struct implements the Connector trait defined by Dozer, ensuring compatibility and consistent behavior across different connectors.
Comprehensive tests: The PR includes comprehensive unit tests in the mysql_cdc_tests.rs file to validate the functionality and correctness of the MySQL CDC connector implementation.
Integration with Dozer: The MySQL CDC connector is integrated into the Dozer platform, allowing users to configure and use it seamlessly alongside other connectors and components.
By adding the MySQL CDC connector in Rust, we expand the range of supported data sources in Dozer and empower users to perform real-time data processing and integration tasks using MySQL CDC. This PR brings the necessary implementation, tests, and integration to accomplish this goal effectively and reliably.

**Comment by snork-alt** [comment]
Closing this as it doesn't meet requirements

**Comment by feliciien** [comment]
Ok I'm still working on i'mlearning how to use MySQL cdc if no one made a PR I will do it If I finish 
Can you give me more details and some helpful link for me.

**Comment by snork-alt** [comment]
@feliciien I will leave it open then. Be sure to implement it in Rust and have comprehensive tests. Thanks

**Pull request closed without merging**
