### PR TITLE
Support for syntax function<Type>() in SQL

### LINKED ISSUE #1677: Support for syntax `function<Type>()` in SQL
## Current state
When UDFs are defined in Dozer, it is imperative for each UDF to specify a return type in Rust code. However, when dynamic UDFs are defined (like Python), it is impossible to specify a return type at compile type. The current mechanism to specify the return type is to include it as an argument of the function. For example:

```
 my_function(arg1, arg2, 'int')
```
This is not very intuitive. 

## New format
We want to extend the SQL parser support the following format:

```
my_function<int>(arg1, arg2)
```
During the parsing phase, when a function call is encountered, the new parse implementation should return an `Option<String>` representing the specified type. If no type is present in the call, `Option` should be `None`.

We currently use DataFusion's SQL parser. The new implementation requires forking the current parser. The new parse can be placed as a sub-project of Dozer.

### PR DESCRIPTION
**Pull request by abcpro1**
closes #1677

The new syntax was implemented in a local fork of the `sqlparser-rs` crate with a special SQL dialect named `DozerDialect`, which is based on the ANSI dialect. 

Tests have been added as well.

/claim #1677

### CODE REVIEW

**Comment by snork-alt** [comment]
@abcpro1 some tests are failing

**Comment by abcpro1** [comment]
@snork-alt failures resolved. Please re-run the CI jobs.

**Comment by abcpro1** [comment]
@snork-alt please trigger the CI jobs again. I have fixed some additional formatting issues.

**Comment by snork-alt** [comment]
@mediuminvader can you review and merge ?

**Comment by abcpro1** [comment]
@mediuminvader sure.

**Comment by abcpro1** [comment]
@mediuminvader Can you merge this pull request https://github.com/getdozer/sqlparser-rs/pull/1 please?

**Comment by mediuminvader** [comment]
> @mediuminvader Can you merge this pull request https://github.com/getdozer/sqlparser-rs/pull/1 please?

Done

**Comment by abcpro1** [comment]
@mediuminvader Thanks! Can you please trigger the CI jobs that need approval?

**Review by mediuminvader — APPROVED** [review]

**Pull request merged**
