### PR TITLE
feat: Check for running environment

### PR DESCRIPTION
**Pull request by mediuminvader**

### CODE REVIEW

**Review by chubei — COMMENTED** [review]
I don't get this. Where's `DOZER_ENV` env var set?

**Comment by mediuminvader** [comment]
> I don't get this. Where's `DOZER_ENV` env var set?

@chubei I'm assuming it's special var we're going to set up on the cluster, and not on local run.
Hence running on our cluster it will give the right value, running on local it just give back "local".

**Comment by chubei** [comment]
How are we going to distinguish between if it's us developing or an actual user using it?

**Comment by mediuminvader** [comment]
We don't need to recognize our development, just the cloud run.
But we could do that using a special VAR value to identify our own run.

**Review by chubei — APPROVED** [review]
Got it! Thanks for the explanation!

**Pull request merged**
