### PR TITLE
fix: chrono version update

### PR DESCRIPTION
**Pull request by Kurtsley**
I realize this code in helper.rs is a hack, but the chrono team is working on a more elegant solution.

                Field::Timestamp(
                    Utc.fix().with_ymd_and_hms(2001, 1, 1, 0, 4, 0).unwrap()
                        + Duration::milliseconds(42),
                ),

### CODE REVIEW

**Comment by mediuminvader** [comment]
Thank you Kurtsley! 
There are still a couple of errors related to chrono deprecated functions, do you mind to fix 'em as well?

```
error: use of deprecated associated function `dozer_types::chrono::NaiveDate::from_ymd`: use `from_ymd_opt()` instead
  --> dozer-ingestion/src/connectors/snowflake/connection/client.rs:97:43
   |
97 |                     let date = NaiveDate::from_ymd(
   |                                           ^^^^^^^^
   |
   = note: `-D deprecated` implied by `-D warnings`

error: use of deprecated associated function `dozer_types::chrono::NaiveTime::from_hms_nano`: use `from_hms_nano_opt()` instead
   --> dozer-ingestion/src/connectors/snowflake/connection/client.rs:102:43
    |
102 |                     let time = NaiveTime::from_hms_nano(
    |                                           ^^^^^^^^^^^^^

error: could not compile `dozer-ingestion` due to 2 previous errors
```

**Comment by Kurtsley** [comment]
Yes, I will check that out.

**Comment by mediuminvader** [comment]
Hi @Kurtsley, I'm not sure it's safe to just unwrap() the values, in case the LocalResult is None or Ambiguous it will panic, we should handle these cases.
I have created a DeserializationError::DateTime for this.

**Comment by Kurtsley** [comment]
I can admit that I am not well versed in error handling in rust, and am unsure how to implement this without unwrap. I will step aside and learn from the eventual solution.

**Comment by mediuminvader** [comment]
@Kurtsley no worries, thank you for what you have done so far, I will update you when the PR is closed so you can review how the errors are handled!

**Comment by mediuminvader** [comment]
@Kurtsley check #793

**Pull request closed without merging**
